@startuml
'https://plantuml.com/class-diagram
interface List {
+ add(e:E) : boolean
+ clear() : void
+ getCount() : int
}

class TemperaturVerlauf {
+ TemperaturVerlauf()
}

List <-- TemperaturVerlauf
@enduml