@startuml
'https://plantuml.com/class-diagram
interface List {

}

class TemperaturVerlauf {
+ TemperaturVerlauf()
+ add(e:E) : boolean
+ clear() : void
+ getCount() : int
}

List <-- TemperaturVerlauf
@enduml